
services:
  # MariaDB Database
  db:
    image: mariadb:10.3
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --max_connections=1000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: medwaste123
      MYSQL_DATABASE: erpnext_db
      MYSQL_USER: erpnext
      MYSQL_PASSWORD: erpnext123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - erpnext-network
    ports:
      - "3307:3306"

  # Redis Cache
  redis_cache:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - redis_cache_data:/data
    networks:
      - erpnext-network

  # Redis Queue
  redis_queue:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - redis_queue_data:/data
    networks:
      - erpnext-network

  # ERPNext Backend
  erpnext:
    image: frappe/erpnext:latest
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=erpnext_db
      - DB_ROOT_PASSWORD=medwaste123
      - DB_PASSWORD=erpnext123
      - REDIS_CACHE_URL=redis://redis_cache:6379
      - REDIS_QUEUE_URL=redis://redis_queue:6379
      - FRAPPE_SITE_NAME_HEADER=localhost
      - ADMIN_PASSWORD=admin123
      - INSTALL_APPS=erpnext
      - DB_TIMEOUT=120
      - MYSQL_CONNECT_TIMEOUT=60
    volumes:
      - erpnext_data:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
    networks:
      - erpnext-network
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_started
      redis_queue:
        condition: service_started
    ports:
      - "8081:8000"

  # ERPNext Worker (Background Jobs)
  worker:
    image: frappe/erpnext:latest
    restart: unless-stopped
    command: ["bench", "worker", "--queue", "default,long,short"]
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=erpnext_db
      - DB_PASSWORD=erpnext123
      - REDIS_CACHE_URL=redis://redis_cache:6379
      - REDIS_QUEUE_URL=redis://redis_queue:6379
      - DB_TIMEOUT=120
      - MYSQL_CONNECT_TIMEOUT=60
    volumes:
      - erpnext_data:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
    networks:
      - erpnext-network
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_started
      redis_queue:
        condition: service_started

  # ERPNext Scheduler (Cron Jobs)
  scheduler:
    image: frappe/erpnext:latest
    restart: unless-stopped
    command: ["bench", "schedule"]
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=erpnext_db
      - DB_PASSWORD=erpnext123
      - REDIS_CACHE_URL=redis://redis_cache:6379
      - REDIS_QUEUE_URL=redis://redis_queue:6379
      - DB_TIMEOUT=120
      - MYSQL_CONNECT_TIMEOUT=60
    volumes:
      - erpnext_data:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
    networks:
      - erpnext-network
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_started
      redis_queue:
        condition: service_started

  # Nginx Proxy Manager with Web UI
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin Web UI
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "erpnext"
      DB_MYSQL_PASSWORD: "erpnext123"
      DB_MYSQL_NAME: "npm_db"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - erpnext-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  redis_cache_data:
  redis_queue_data:
  erpnext_data:
  erpnext_logs:
  npm_data:
  npm_letsencrypt:

networks:
  erpnext-network:
    driver: bridge
