
services:
  # MariaDB Database
  db:
    image: mariadb:10.3
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --max_connections=1000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - erpnext-network
    ports:
      - "${DB_EXTERNAL_PORT}:3306"

  # Redis Cache
  redis_cache:
    image: redis:6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
      interval: 30s
    volumes:
      - redis_cache_data:/data
    networks:
      - erpnext-network

  # Redis Queue
  redis_queue:
    image: redis:6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
      interval: 30s
    volumes:
      - redis_queue_data:/data
    networks:
      - erpnext-network

  # ERPNext Backend
  erpnext:
    image: frappe/erpnext:latest
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}
      - REDIS_QUEUE_URL=${REDIS_QUEUE_URL}
      - FRAPPE_SITE_NAME_HEADER=localhost
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_APPS=${INSTALL_APPS}
      - DB_TIMEOUT=${DB_TIMEOUT}
      - MYSQL_CONNECT_TIMEOUT=${MYSQL_CONNECT_TIMEOUT}
      - TZ=${TZ}
    volumes:
      - erpnext_data:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/method/ping || exit 1"]
      timeout: 30s
      retries: 5
      interval: 60s
      start_period: 120s
    networks:
      - erpnext-network
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
      redis_queue:
        condition: service_healthy
    ports:
      - "${ERPNEXT_EXTERNAL_PORT}:${ERPNEXT_PORT}"

  # ERPNext Worker (Background Jobs)
  worker:
    image: frappe/erpnext:latest
    restart: unless-stopped
    command: ["bench", "worker", "--queue", "default,long,short"]
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}
      - REDIS_QUEUE_URL=${REDIS_QUEUE_URL}
      - DB_TIMEOUT=${DB_TIMEOUT}
      - MYSQL_CONNECT_TIMEOUT=${MYSQL_CONNECT_TIMEOUT}
      - TZ=${TZ}
    volumes:
      - erpnext_data:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
    networks:
      - erpnext-network
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
      redis_queue:
        condition: service_healthy
      erpnext:
        condition: service_healthy

  # ERPNext Scheduler (Cron Jobs)
  scheduler:
    image: frappe/erpnext:latest
    restart: unless-stopped
    command: ["bench", "schedule"]
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}
      - REDIS_QUEUE_URL=${REDIS_QUEUE_URL}
      - DB_TIMEOUT=${DB_TIMEOUT}
      - MYSQL_CONNECT_TIMEOUT=${MYSQL_CONNECT_TIMEOUT}
      - TZ=${TZ}
    volumes:
      - erpnext_data:/home/frappe/frappe-bench/sites
      - erpnext_logs:/home/frappe/frappe-bench/logs
    networks:
      - erpnext-network
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
      redis_queue:
        condition: service_healthy
      erpnext:
        condition: service_healthy

  # Nginx Proxy Manager with Web UI
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"     # HTTP
      - "${NGINX_HTTPS_PORT}:443"   # HTTPS
      - "${NGINX_ADMIN_PORT}:81"     # Admin Web UI
    environment:
      DB_MYSQL_HOST: "${DB_HOST}"
      DB_MYSQL_PORT: ${DB_PORT}
      DB_MYSQL_USER: "${DB_USER}"
      DB_MYSQL_PASSWORD: "${DB_PASSWORD}"
      DB_MYSQL_NAME: "${NPM_DB_NAME}"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - erpnext-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  redis_cache_data:
  redis_queue_data:
  erpnext_data:
  erpnext_logs:
  npm_data:
  npm_letsencrypt:

networks:
  erpnext-network:
    driver: bridge
